# Environment Settings
gpu_id: '0'                     # (str) The id of GPU device(s).
worker: 0                       # (int) The number of workers processing the data.
use_gpu: True                   # (bool) Whether or not to use GPU.
seed: 2023                      # (int) Random seed.
state: INFO                     # (str) Logging level.
reproducibility: True           # (bool) Whether or not to make results reproducible.
data_path: '/home/WFGR/dataset/'           # (str) The path of input dataset.
checkpoint_dir: '/home/WFGR/saved/'         # (str) The path to save checkpoint file.
show_progress: True             # (bool) Whether or not to show the progress bar of every epoch.
save_dataset: True             # (bool) Whether or not to save filtered dataset.
saved_model_file: True
dataset_save_path: 'saved_dataset'            # (str) The path of saved dataset.
save_dataloaders: True         # (bool) Whether or not save split dataloaders.
dataloaders_save_path: 'saved_dataloaders'        # (str) The path of saved dataloaders.
log_wandb: True                # (bool) Whether or not to use Weights & Biases(W&B).
wandb_project: 'WFGR'        # (str) The project to conduct experiments in W&B.
shuffle: True                   # (bool) Whether or not to shuffle the training data before each epoch.

# Training Settings
epochs: 1000                     # (int) The number of training epochs.
# pretrain_epochs: 10
# save_step: 5
train_batch_size: 4048          # (int) The training batch size.
learner: adam                   # (str) The name of used optimizer.
learning_rate: 0.001            # (float) Learning rate.
train_neg_sample_args:          # (dict) Negative sampling configuration for model training.
  distribution: uniform         # (str) The distribution of negative items.
  sample_num: 1                 # (int) The sampled num of negative items.
  alpha: 1.0                    # (float) The power of sampling probability for popularity distribution.
  dynamic: False                # (bool) Whether to use dynamic negative sampling.
  candidate_num: 0              # (int) The number of candidate negative items when dynamic negative sampling.
eval_step: 1                    # (int) The number of training epochs before an evaluation on the valid dataset.
stopping_step: 1000               # (int) The threshold for validation-based early stopping.
clip_grad_norm: ~               # (dict) The args of clip_grad_norm_ which will clip gradient norm of model. 
weight_decay: 0.0005               # (float) The weight decay value (L2 penalty) for optimizers.
loss_decimal_place: 4           # (int) The decimal place of training loss.
require_pow: False              # (bool) Whether or not to perform power operation in EmbLoss.
enable_amp: False               # (bool) Whether or not to use mixed precision training.
enable_scaler: False            # (bool) Whether or not to use GradScaler in mixed precision training.
transform: ~                    # (str) The transform operation for batch data process.
embedding_size: 64              # (int)
# additional_feat_suffix: [useremb]
load_col: 
    inter: ['user_id', 'item_id', 'rating', 'timestamp']
# alias_of_user_id: [uid]
# preload_weight:
    # uid: user_emb

# Evaluation Settings
eval_args:                      
  # (dict) 4 keys: group_by, order, split, and mode
  # (dict) The splitting strategy ranging in ['RS','LS'].
  
  # base split
  # split: {'RS':[0.8,0.1,0.1]}
  
  # Custom_ml-100k_1
  split: {'RS':[0.675,0.075,0.25]}
  # Custom_ml-100k_2
  
  # split: {'RS':[0.72,0.08,0.2]}
  
  # Custom_ml-100k_3
  # split: {'RS':[0.775,0.1,0.125]}
  
  # Custom_ml-100k_4
  # split: {'RS':[0.81,0.09,0.1]}
  
  # Train_1_ml-1m
  # split: {'RS':[0.675,0.075,0.25]}
  
  # Train_2_ml-1m
  # split: {'RS':[0.72,0.08,0.2]}
  
  # Train_3_ml-1m
  # split: {'RS':[0.775,0.1,0.125]}
  
  # Train_4_ml-1m
  # split: {'RS':[0.81,0.09,0.1]}
  
  group_by: user                # (str) The grouping strategy ranging in ['user', 'none'].
  order: RO                     # (str) The ordering strategy ranging in ['RO', 'TO'].
  mode: full                    # (str) The evaluation mode ranging in ['full','unixxx','popxxx','labeled'].
repeatable: False               # (bool) Whether to evaluate results with a repeatable recommendation scene.
# Recall, MRR, NDCG, Hit, MAP, Precision, GAUC, ItemCoverage, AveragePopularity, GiniIndex, ShannonEntropy, TailPercentage
# (list or str) Evaluation metrics.
metrics: ["Recall","MRR","NDCG","Hit","MAP","Precision","GAUC","ItemCoverage","AveragePopularity","GiniIndex","ShannonEntropy","TailPercentage"]
topk: [20]                      # (list or int or None) The value of k for topk evaluation metrics.
valid_metric: Recall@20            # (str) The evaluation metric for early stopping. 
valid_metric_bigger: True       # (bool) Whether to take a bigger valid metric value as a better result.
eval_batch_size: 4048           # (int) The evaluation batch size.
metric_decimal_place: 4         # (int) The decimal place of metric scores.


