# embedding_size: 64
# n_layers: 2
# reg_weight: 1e-4
# lambda: 0.5
# eps: 0.1
# temperature: 0.2

embedding_size: 64
learning_rate: 0.002
n_layers: 2
reg_weight: 0.0001
temperature: 0.05
lambda: 1e-5
eps: 0.1